### ISSUE TITLE
Libxml2 error messages not forwarded to the client during xml parsing

### ISSUE THREAD

**Issue by krocard** [01org/parameter-framework#122]
Libxml2 can report errors through its serializing context (correctly handled by the PF) or through either:
 - xmlSetGenericErrorFunc (subscribe with [xmlSetGenericErrorFunc](http://xmlsoft.org/html/libxml-xmlerror.html#xmlSetGenericErrorFunc))
 - xmlSetStructuredErrorFunc (subscribe with [xmlSetStructuredErrorFunc](http://xmlsoft.org/html/libxml-xmlerror.html#xmlSetStructuredErrorFunc))
([used in the pfw](https://github.com/01org/parameter-framework/blob/master/xmlserializer/XmlDocSource.cpp#L218)).

Multiple problems arise:
 - the error callback is set [only if the xml is validated](https://github.com/01org/parameter-framework/blob/master/xmlserializer/XmlDocSource.cpp#L218)
        => all other potential errors are lost
 - only the error message is logged, [not its context](https://github.com/01org/parameter-framework/blob/master/xmlserializer/XmlDocSource.cpp#L239) (level, file, line number, ...)
 - error is [logged to stdout](https://github.com/01org/parameter-framework/blob/master/xmlserializer/XmlDocSource.cpp#L239) instead of being returned to the client.

Proposed solution:
-  [ ] move schema validation in `CXmlDocSource::mkXmlDoc` after the xinclude processing. Or at least in `CXmlDocSource::validate` if the previous could not be done for some reason.
- [ ] use `xmlSetGenericErrorFunc` instead of `xmlSetStructuredErrorFunc` to have automatic error formating.
- [ ] no longer log to `stdout` but rather to `serializingContext`
- [ ] rework `CXmlSerializingContext` to be able to set an error context *before* setting the error message. (rename `appendLineToError` to `appendContextLine` and have the error separated from the context string).

**Comment by dawagner** [comment]
Care to provide some details ? :)

**Comment by krocard** [comment]
Miss clicked, sorry. I am currently writing it.

**Comment by dawagner** [comment]
Done in #150
