### ISSUE TITLE
Avoid failing build for warning in an integration context.

### ISSUE THREAD

**Issue by krocard** [01org/parameter-framework#159]
Forbidding warnings (Werror) when modifying the PF is beneficial for code quality. Nevertheless when integrating the PF in an other component, one should not have to modify the FP code to compile it if there is only warnings.

Proposition: Add a PF option "FAIL_BUILD_ON_WARNING" (or maybe "PF_DEVELOPEMENT" ?) default to true (to make sure external contributers do not introduce warnings) that enables Werrors flags.

**Comment by krocard** [comment]
Should be fixed by #310.

**Comment by dawagner** [comment]
Done.
