### ISSUE TITLE
Parameter-framework bindings fails to build vs swig 3.0 or higher

### ISSUE THREAD

**Issue by mgaio** [01org/parameter-framework#166]
According swig release note, 
%nestedworkaround is deprecated and %flatnested should be use instead.
As -Werror flag is enabled the usage of deprecated %nestedworkaround breaks the build

**Comment by krocard** [comment]
This is more a feature request than a bug as swig 3 is not officially supported.

**Comment by krocard** [comment]
This was fixed in #314, available since release v3.1.0.

**Comment by krocard** [comment]
Beware though that *swig 3 is not officially supported* as not tested in the CI.
