### ISSUE TITLE
Provide .cmake files for clients and plugin to easily compile/link against the Parameter Framework

### ISSUE THREAD

**Issue by dawagner** [01org/parameter-framework#169]
Right now, clients and plugins writers need to manually use find_path() and such in their CMake makefiles. A helper file would be nicer.

**Comment by dawagner** [comment]
Stretch goal for the windows port.

**Comment by krocard** [comment]
With #200 libparameter.so header are registered in cmake. Thus I expect some a way to generate a correct FindParameter.cmake exist.

**Comment by dawagner** [comment]
There is an `install(EXPORTS ...` command that might be worth looking at.

**Comment by dawagner** [comment]
Fixed in v3.2.5 :)
