### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [01org/parameter-framework#181]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [CMessage::allocateData](https://github.com/01org/parameter-framework/blob/7ba789f53ed8c8070a218785bc6539af09d9b35f/remote-processor/Message.cpp#L267 "CMessage::allocateData function")
* [CParameterBlackboard::setSize](https://github.com/01org/parameter-framework/blob/7ba789f53ed8c8070a218785bc6539af09d9b35f/parameter/ParameterBlackboard.cpp#L44 "CParameterBlackboard::setSize")

**Comment by dawagner** [comment]
Agreed. The "allocateData" one is going away soon anyway.

We can also avoid some deletes using smart pointers.

**Comment by krocard** [comment]
Second point is fixed by #178 by using a std::vector instead of a C style array.

**Comment by krocard** [comment]
Both have been fixed by using `std::vector` instead of manually managed buffer.

**Comment by elfring** [comment]
Thanks for your small source code improvement.

**Comment by krocard** [comment]
You are welcome. Thank for the bug reports by the way.
