### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [01org/parameter-framework#182]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [CParameterMgr constructor](https://github.com/01org/parameter-framework/blob/4b9104529736082a6a2671b7f12bc4cd5fe54da1/parameter/ParameterMgr.cpp#L324)
- [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") ⇒ [CAutoLock](https://github.com/01org/parameter-framework/blob/7ba789f53ed8c8070a218785bc6539af09d9b35f/parameter/AutoLock.h#L37)

**Comment by dawagner** [comment]
Hi,

We know about them and handling them has been a pending item. We are moving to C++11 and will be using its thread library. It will fix this particular issue.

e.g.: [CAutoLock](https://github.com/01org/parameter-framework/blob/windows_port/parameter/AutoLock.h)

**Comment by elfring** [comment]
Should this issue be kept open until the item will be completely fixed?

**Comment by dawagner** [comment]
Why not.

**Comment by elfring** [comment]
Are there [any more update candidates](https://github.com/01org/parameter-framework/blob/7ba789f53ed8c8070a218785bc6539af09d9b35f/bindings/c/ParameterFramework.cpp#L371 "Update candidate: pfwGetStringParameter()") left over?

**Comment by krocard** [comment]
It should have all been fixed since the code now compiles also on Windows natively thanks to c++11 thread support.

**Comment by elfring** [comment]
How do you think about to care also for [a failed call of a function like "strdup"](https://github.com/01org/parameter-framework/blob/master/bindings/c/ParameterFramework.cpp#L336 "Update candidate: pfwGetStringParameter()")?
