### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [01org/parameter-framework#183]
Would you like to [replace any double quotes](https://github.com/01org/parameter-framework/blob/4b9104529736082a6a2671b7f12bc4cd5fe54da1/parameter/ParameterMgr.cpp#L30 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by dawagner** [comment]
Hi,

It is a common practice to put quotes around headers located in the same directory as the source file - which is the case for most of the files in the Parameter Framework. When looking at the reference documentation, the behaviour of both ways are implementation-defined anyway.

However, there are some cases where the included file is not in the same directory (e.g. ParameterHandle.h). We could consider it; we'll discuss it internally.

BTW, may I ask how you discovered this project ? :) I only know your name from seeing you on the coccinelle mailing-list ;)

**Comment by krocard** [comment]
I do not get why that would be any better. As rightfully quoted in the [answer that quotes the norm](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename#answer-77092), the two format (`""` & `<>`) are searching in implementation defined location. With `""` falbacking to `<>` if nothing is find. Thus from a norm point of view I do not see why `<>`  would be better.

> It is a common practice to put quotes around headers located in the same directory as the source file
Clang even raises a warning when including same directory files with `<>`.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by krocard** [comment]
> How do you think about to avoid "a duplicated file search" here?

You are right, from a strict norm point of view `""` inclusion could lead to a potential inclusion conflict that would not occur with `<>`. But that is just because `""` is a superset of `<>`.

> Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

Exactly. From my point of view, `""` explicitness that the queried header is in the _same_ library is far more valuable that a possibly inclusion conflict.

> You can prepend directories to the list of quote directories with the `-iquote` option. 

Interesting. I did not know this. Need to check if it supported by clang & visual studio cl.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by krocard** [comment]
> Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
Has you quoted, they may (implementation defined). On clang and gcc at least they are searched in the source file directory.

> Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?
If there is a measurable speed difference, I am not aware it. Have you experienced such inconvenient?

To summarize (goal: include a header from the library being compiled):
 - `""` includes
   * Pros:
     + Explicitness that the queried header is in the same library (convention enforced by Clang)
   * Cons:
     + Potentially slower
     + Search locations is compilator dependent
     + user specification of locations is not widely used (seems `-iquote` exist on gcc)
 - `<>` includes
   * Pros:
      + user specification of locations is widely used (`-I` gcc/clang)
   * Cons:
      + Search locations is compilator dependent
      + Does not explicit that the header is from the same library

I agree that `""` is not a silver bullet to _explicit that the header is from the same library_ but as far as I am concerned, advantages exceed the risk that the code might be broken for an exotic compiler/environment.

+ `""` & `<>` search locations are both implementation defined. So _if_ this theoretical exotic compiler does not respect the `""` convention, it might also not support the `<>` "search for a file with this name" convention.

PS: Just a curiosity question: How did you learn about this project ?

**Comment by elfring** [comment]
>user specification of locations is widely used

Can a parameter like "`-I`" give you a bit more safety for the reuse of the desired header files for a software build configuration?


>How did you learn about this project ?

I came along by the GitHub interface during my attempt to improve various software.

**Comment by krocard** [comment]
> Can a parameter like "-I" give you a bit more safety for the reuse of the desired header files for a software build configuration?

If I understand, you are proposing to add the `make` equivalent of `-I $(dirname $<)` (ie: explicitly add the source folder) in the CMakeList.txt. If so, I fully agree with you.

**Task:** Add the source directory in the include directory list.
**Note:** Add `include_directories(.)` in the CMakeList.txt most of the time.
**Rational:** To support odd compilers to are not searching in the source dir for headers.

**Comment by elfring** [comment]
>Add `include_directories(.)` in the CMakeList.txt

I would find the "dot" strange as a command parameter there.

Where should header files be usually stored for a software framework?

**Comment by krocard** [comment]
> I would find the "dot" strange as a command parameter there.
Our CMakeList.txt are in the source folder directly. We are planning to split the files in a classic `include`,`src`,`test` pattern but we haven't yet.

> Where should header files be usually stored for a software framework?
We are talking about how to compile the framework, not how user should link against it here. Not sure I understood your question though.

**Comment by elfring** [comment]
Would you like to distinguish anyhow if the framework header files will be reused from an installed location (or component directory) instead of being picked up from a development folder anywhere else?

**Comment by dawagner** [comment]
When the "libparameter" is compiled and installed, the public headers are installed to a well-known directory (prefixed by the value of CMAKE_INSTALL_PREFIX). It is then up to the library that wants to use the framework to search for the headers in that well-known directory.

So I guess the answer to your question is "yes".

**Comment by elfring** [comment]
Does it matter for you if angle brackets will be used after the required header files were installed in the "well-known directory"?

**Comment by dawagner** [comment]
I don't think so, since this choice is left to a 3rd party. However, the usual way of doing this is to use angle brackets.

**Comment by krocard** [comment]
After team discussion, supporting of odd compiler that are so strange that they do not follow the `"" == same directory` convention is not planed, nor wanted.
Additionally how our headers are included (`""` vs `<>`) by other project is not our concerned (matter of coding style).
