### ISSUE TITLE
Multiple Name attribute during xml export

### ISSUE THREAD

**Issue by krocard** [01org/parameter-framework#42]
In xml an attribute must be unique in an node. IE: `<SomeTag Name="foo" Name="foo"/>` is not xml compliant.

When exporting the system class in xml (and possibly others, I have not tested) the system class name is duplicated. IE: `<SystemClass Name="audio" Name="audio">`. The rest of the xml is correct.

**Comment by dawagner** [comment]
Solved by 36423a49fdde5755faea5914e554b64363034b0c
