### ISSUE TITLE
Find python with FindPythonInterp

### ISSUE THREAD

**Issue by krocard** [01org/parameter-framework#64]
The python interpreter is located with `find_program(python2)`:
https://github.com/01org/parameter-framework/blob/master/test/test-fixed-point-parameter/CMakeLists.txt#L29

A better way would be to use `FindPythonInterp.cmake`, setting `Python_ADDITIONAL_VERSIONS` to 2. See http://www.cbica.upenn.edu/sbia/software/basis/apidoc/latest/FindPythonInterp_8cmake.html

(it's an posible improvement, not a bug)

**Comment by dawagner** [comment]
Done.
