### ISSUE TITLE
Document XML coding style

### ISSUE THREAD

**Issue by Makohoek** [01org/parameter-framework#71]
We have a repo, https://github.com/01org/parameter-framework-samples/ which contains some samples which can be used with the parameter-framework.

However, the coding style/best practices to write those samples are not documented on GitHub.
Maybe we should port our internal wiki towards the GitHub wiki ?

**Comment by sguiriec** [comment]
Wiki is now up to date with XML and PFW files coding Rule. Please refer to the next page
https://github.com/01org/parameter-framework/wiki/XML-and-PFW-Coding-Rules
