### ISSUE TITLE
Criterion type interface displays erroneous states through getFormattedState method

### ISSUE THREAD

**Issue by clero** [01org/parameter-framework#74]
When using `getFormattedState` method from ISelectionCriterionInterface some pipes groups can be displayed. This bug is well known and some fixes are present in 770f8e13f7608b4b7f356c0bcf662ba6392b5c02 and 75461a26a74a4d9cb60020ccfcb2a5a4ec0961bd patches. Nevertheless the source is not patched.
In `getFormattedState`, the criterion state value passed as parameter is not checked and can contain unknown states. For example, a criterion with two states numbered 1 and 2 can format the state 8 which will lead to something like " State1 | State2 | | | ".

**Investigation:**
It seems that `getLiteralValue` call in `getFormattedState` is not checked. Checking the result will correct the bug. Nevertheless, it can be useful to rework Criterion interfaces which is error prone. Indeed, the internal state representation of a criterion is exposed to the client and not check (neither in setCriterionState).

**Comment by clero** [comment]
In fact, this bug is patched here 7287dc8687b92f54dd53456a251e0ae90a261ec0 but we can keep this issue with a question label about the criterion interface.

**Comment by dawagner** [comment]
Please verify that is fixed by #52 (merged)

**Comment by dawagner** [comment]
If it is fixed, I'll close the ticket. Please feel free to open another one relative to the "error-prone criterion interface".

**Comment by dawagner** [comment]
I'm closing this since it is supposedly fixed and nobody complained about it in more than a year.
